ERROR 2021-01-06 20:46:58,520: report_part_c.docx does not exist.
INFO 2021-01-06 20:46:58,536: Successfully loaded benchmark labels data.
INFO 2021-01-06 20:46:58,551: Successfully loaded queries data.
ERROR 2021-01-06 20:46:59,848: The following error occured while testing the module search_engine_4.
ERROR 2021-01-06 20:46:59,863: No module named 'thesaurus'
Traceback (most recent call last):
  File "C:/Users/shaha/Desktop/Search_Engine-master/test_part_c_students.py", line 95, in <module>
    se = importlib.import_module(engine_module)
  File "C:\Users\shaha\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\shaha\Desktop\Search_Engine-master\search_engine_4.py", line 8, in <module>
    from searcher import Searcher
  File "C:\Users\shaha\Desktop\Search_Engine-master\searcher.py", line 3, in <module>
    from thesaurus import Word
ModuleNotFoundError: No module named 'thesaurus'
DEBUG 2021-01-06 20:46:59,863: Total runtime was: 0:00:01.343469
